import { useState, useEffect, useRef, useCallback, type CSSProperties } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/App";
import { useRedWs } from "@/hooks/useRedWs";
import { useBlueWs } from "@/hooks/useBlueWs";
import { redApi } from "@/api/redApi";
import { blueApi } from "@/api/blueApi";
import { authApi } from "@/api/authApi";
import type { ToolCall, LogEntry, PendingFix, ScoreData } from "@/types";

function buildArenaReport(opts: {
  target: string;
  username: string;
  scores: ScoreData;
  redLogs: LogEntry[];
  blueLogs: LogEntry[];
  redToolCalls: ToolCall[];
  blueToolCalls: ToolCall[];
  redMessages: { role: string; text: string }[];
  blueMessages: { role: string; text: string }[];
  pendingFixes: PendingFix[];
}): string {
  const now = new Date().toLocaleString();
  const line = (n = 70) => "=".repeat(n);
  const dash = (n = 70) => "-".repeat(n);
  const fmt = (ts: string) => {
    try { const d = new Date(ts); return d.toLocaleTimeString(); } catch { return ts; }
  };

  const rows: string[] = [];
  rows.push(line());
  rows.push("   HTF ARENA — BATTLE REPORT");
  rows.push("   Red vs Blue Cyber Battleground");
  rows.push(line());
  rows.push(`  Generated  : ${now}`);
  rows.push(`  Operator   : ${opts.username}`);
  rows.push(`  Target     : ${opts.target}`);
  rows.push(`  Red Score  : ${opts.scores.red_score}`);
  rows.push(`  Blue Score : ${opts.scores.blue_score}`);
  rows.push(`  Winner     : ${opts.scores.red_score > opts.scores.blue_score ? "RED TEAM" : opts.scores.blue_score > opts.scores.red_score ? "BLUE TEAM" : "DRAW"}`);
  rows.push("");

  // ── RED AGENT ──────────────────────────────────────────────────────
  rows.push(dash());
  rows.push("  1. RED AGENT ACTIVITY");
  rows.push(dash());
  rows.push("");
  rows.push(`  Tool Calls : ${opts.redToolCalls.length}`);
  rows.push(`  Log Entries: ${opts.redLogs.length}`);
  rows.push("");

  if (opts.redMessages.length > 0) {
    rows.push("  1.1 Operator Commands & Agent Responses");
    rows.push("  " + "-".repeat(40));
    opts.redMessages.forEach(m => {
      const role = m.role === "operator" ? "YOU" : "RED AGENT";
      rows.push(`  [${role}] ${m.text}`);
    });
    rows.push("");
  }

  if (opts.redToolCalls.length > 0) {
    rows.push("  1.2 Tool Executions");
    rows.push("  " + "-".repeat(40));
    opts.redToolCalls.forEach((t, i) => {
      rows.push(`  [${i + 1}] ${t.name} (${t.category}) — ${t.status}`);
    });
    rows.push("");
  }

  if (opts.redLogs.length > 0) {
    rows.push("  1.3 Red Agent Logs");
    rows.push("  " + "-".repeat(40));
    opts.redLogs.forEach(l => {
      rows.push(`  ${fmt(l.timestamp)}  [${l.level}]  ${l.message}`);
    });
    rows.push("");
  }

  // ── BLUE AGENT ─────────────────────────────────────────────────────
  rows.push(dash());
  rows.push("  2. BLUE AGENT ACTIVITY");
  rows.push(dash());
  rows.push("");
  rows.push(`  Tool Calls : ${opts.blueToolCalls.length}`);
  rows.push(`  Log Entries: ${opts.blueLogs.length}`);
  rows.push(`  Pending Fixes: ${opts.pendingFixes.length}`);
  rows.push("");

  if (opts.blueMessages.length > 0) {
    rows.push("  2.1 Defense Terminal Messages");
    rows.push("  " + "-".repeat(40));
    opts.blueMessages.forEach(m => {
      const role = m.role === "system" ? "SYSTEM" : "BLUE AGENT";
      rows.push(`  [${role}] ${m.text}`);
    });
    rows.push("");
  }

  if (opts.blueToolCalls.length > 0) {
    rows.push("  2.2 Defense Tool Executions");
    rows.push("  " + "-".repeat(40));
    opts.blueToolCalls.forEach((t, i) => {
      rows.push(`  [${i + 1}] ${t.name} (${t.category}) — ${t.status}`);
    });
    rows.push("");
  }

  if (opts.pendingFixes.length > 0) {
    rows.push("  2.3 Pending Fixes");
    rows.push("  " + "-".repeat(40));
    opts.pendingFixes.forEach((f, i) => {
      rows.push(`  [${i + 1}] [${f.severity.toUpperCase()}] ${f.category.replace(/_/g, " ")}`);
      rows.push(`       ${f.description}`);
    });
    rows.push("");
  }

  if (opts.blueLogs.length > 0) {
    rows.push("  2.4 Blue Agent Logs");
    rows.push("  " + "-".repeat(40));
    opts.blueLogs.forEach(l => {
      rows.push(`  ${fmt(l.timestamp)}  [${l.level}]  ${l.message}`);
    });
    rows.push("");
  }

  // ── SCORE HISTORY ──────────────────────────────────────────────────
  if (opts.scores.history.length > 0) {
    rows.push(dash());
    rows.push("  3. SCORE HISTORY");
    rows.push(dash());
    rows.push("");
    opts.scores.history.forEach(h => {
      rows.push(`  [${h.team.toUpperCase()}] +${h.points} — ${h.reason}`);
    });
    rows.push("");
  }

  rows.push(line());
  rows.push("  Report generated by: HTF Arena Dashboard");
  rows.push(`  Timestamp: ${now}`);
  rows.push(line());

  return rows.join("\n");
}

function downloadTextFile(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function ArenaDashboard() {
  const { username, logout } = useAuth();
  const nav = useNavigate();
  const red = useRedWs();
  const blue = useBlueWs();

  const [target, setTarget] = useState("http://172.25.8.172:5000");
  const [scores, setScores] = useState<ScoreData>({ red_score: 0, blue_score: 0, history: [] });
  const [pendingFixes, setPendingFixes] = useState<PendingFix[]>([]);
  const [tab, setTab] = useState<"battle" | "scores">("battle");
  const [downloading, setDownloading] = useState(false);
  const [splitPct, setSplitPct] = useState(50);
  const isDragging = useRef(false);
  const containerRef = useRef<HTMLDivElement>(null);

  const onDividerMouseDown = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    isDragging.current = true;
    document.body.style.cursor = "col-resize";
    document.body.style.userSelect = "none";
  }, []);

  useEffect(() => {
    const onMouseMove = (e: MouseEvent) => {
      if (!isDragging.current || !containerRef.current) return;
      const rect = containerRef.current.getBoundingClientRect();
      const pct = ((e.clientX - rect.left) / rect.width) * 100;
      setSplitPct(Math.min(80, Math.max(20, pct)));
    };
    const onMouseUp = () => {
      if (!isDragging.current) return;
      isDragging.current = false;
      document.body.style.cursor = "";
      document.body.style.userSelect = "";
    };
    window.addEventListener("mousemove", onMouseMove);
    window.addEventListener("mouseup", onMouseUp);
    return () => {
      window.removeEventListener("mousemove", onMouseMove);
      window.removeEventListener("mouseup", onMouseUp);
    };
  }, []);

  const [redInput, setRedInput] = useState("");
  const [redLoading, setRedLoading] = useState(false);
  const [redMessages, setRedMessages] = useState<{ role: string; text: string }[]>([]);
  const redTermRef = useRef<HTMLDivElement>(null);
  const [blueMessages, setBlueMessages] = useState<{ role: string; text: string }[]>([]);
  const blueTermRef = useRef<HTMLDivElement>(null);
  const [blueStarted, setBlueStarted] = useState(false);

  const redWasConnected = useRef(false);
  useEffect(() => {
    if (red.connected && !redWasConnected.current) { setRedMessages([]); setRedInput(""); }
    redWasConnected.current = red.connected;
  }, [red.connected]);

  const blueWasConnected = useRef(false);
  useEffect(() => {
    if (blue.connected && !blueWasConnected.current) { setBlueMessages([]); setPendingFixes([]); setBlueStarted(false); }
    blueWasConnected.current = blue.connected;
  }, [blue.connected]);

  useEffect(() => { redTermRef.current?.scrollTo(0, redTermRef.current.scrollHeight); }, [redMessages]);
  useEffect(() => { blueTermRef.current?.scrollTo(0, blueTermRef.current.scrollHeight); }, [blueMessages, pendingFixes]);

  useEffect(() => {
    const i = setInterval(async () => { try { setScores(await authApi.scores()); } catch { } }, 5000);
    return () => clearInterval(i);
  }, []);

  const handleDownloadReport = async () => {
    setDownloading(true);
    try {
      const report = buildArenaReport({
        target,
        username: username ?? "unknown",
        scores,
        redLogs: red.logs,
        blueLogs: blue.logs,
        redToolCalls: red.toolCalls,
        blueToolCalls: blue.toolCalls,
        redMessages,
        blueMessages,
        pendingFixes,
      });
      const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
      downloadTextFile(report, `htf-arena-report-${ts}.txt`);
    } finally {
      setDownloading(false);
    }
  };

  const sendRed = async () => {
    const txt = redInput.trim();
    if (!txt || redLoading) return;
    setRedInput("");
    setRedMessages(p => [...p, { role: "operator", text: txt }]);
    setRedLoading(true);
    try {
      const res = await redApi.chat(txt, target);
      setRedMessages(p => [...p, { role: "agent", text: res.content || res.reply || res.message || (typeof res === "string" ? res : JSON.stringify(res)) }]);
    } catch (e: any) {
      setRedMessages(p => [...p, { role: "agent", text: `Error: ${e?.message}` }]);
    } finally { setRedLoading(false); }
  };

  const approveFix = async (fixId: string) => {
    setBlueStarted(true);
    try {
      const res = await blueApi.approveFix(fixId);
      setBlueMessages(p => [...p, { role: "agent", text: `Fix applied: ${res.fix_id} — ${res.status}` }]);
      setPendingFixes(p => p.filter(f => f.fix_id !== fixId));
    } catch (e: any) {
      setBlueMessages(p => [...p, { role: "agent", text: `Error: ${e?.message}` }]);
    }
  };

  const approveAll = async () => {
    setBlueStarted(true);
    try {
      const results = await blueApi.approveAll();
      setBlueMessages(p => [...p, { role: "agent", text: `All ${results.length} fixes applied.` }]);
      setPendingFixes([]);
    } catch (e: any) {
      setBlueMessages(p => [...p, { role: "agent", text: `Error: ${e?.message}` }]);
    }
  };

  const sendReportToBlue = async () => {
    setBlueStarted(true);
    setBlueMessages(p => [...p, { role: "system", text: "Receiving Red Team report..." }]);
    try {
      // Step 1: run the sample — populates pending fixes on the server
      const res = await blueApi.runSample();
      // Step 2: fetch pending fixes directly from the server (most reliable)
      const fixes = (await blueApi.pendingFixes()) as PendingFix[];
      setPendingFixes(fixes);
      setBlueMessages(p => [...p, {
        role: "agent",
        text: fixes.length > 0
          ? `Report processed: ${res.total_findings} findings (${res.severity_counts?.critical ?? 0} critical, ${res.severity_counts?.high ?? 0} high). ${fixes.length} fixes queued — click ✓ APPLY or ✓ APPROVE ALL.`
          : `Report processed: ${res.total_findings} findings (${res.severity_counts?.critical ?? 0} critical, ${res.severity_counts?.high ?? 0} high). Analysis complete.`
      }]);
    } catch (e: any) {
      setBlueMessages(p => [...p, { role: "agent", text: `Defense pipeline error: ${e?.message ?? "unknown error"}` }]);
    }
  };

  const redRunning = red.toolCalls.filter(t => t.status === "RUNNING").length;
  const redDone   = red.toolCalls.filter(t => t.status === "DONE").length;
  const blueRunning = blue.toolCalls.filter(t => t.status === "RUNNING").length;
  const blueDone    = blue.toolCalls.filter(t => t.status === "DONE").length;

  const fmtTime = (ts: string) => {
    try { const d = new Date(ts); return `${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}:${String(d.getSeconds()).padStart(2,"0")}`; }
    catch { return ""; }
  };

  const sevColor: Record<string, string> = {
    critical: "var(--red)", high: "var(--orange)", medium: "var(--yellow)", low: "var(--green)",
  };

  return (
    <div className="has-scanline grid-bg" style={{ height: "100vh", display: "flex", flexDirection: "column", overflow: "hidden" }}>

      {/* ═══ TOP BAR ═══ */}
      <header style={topBar}>
        {/* Logo */}
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <div style={logoBadge} className="anim-glow">
            <span style={{ fontSize: 20 }}>&#9876;</span>
          </div>
          <div>
            <div style={{ fontSize: 16, fontWeight: 900, color: "var(--accent)", fontFamily: "var(--font-display)", letterSpacing: 5, textShadow: "0 0 20px var(--accent-glow)" }}>HTF 4.0 ARENA</div>
            <div style={{ fontSize: 8, color: "var(--text-dim)", letterSpacing: 4, fontFamily: "var(--font-ui)", marginTop: 1 }}>RED vs BLUE BATTLEGROUND</div>
          </div>
        </div>

        {/* Tabs + Download */}
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <div style={{ display: "flex", gap: 0, border: "1px solid var(--accent-border)", borderRadius: 6, overflow: "hidden" }}>
            <TabBtn label="⚔ BATTLE" active={tab === "battle"} onClick={() => setTab("battle")} />
            <TabBtn label="🏆 SCOREBOARD" active={tab === "scores"} onClick={() => setTab("scores")} />
          </div>
          <button
            onClick={handleDownloadReport}
            disabled={downloading}
            title="Download full battle report as .txt"
            style={{
              display: "flex", alignItems: "center", gap: 6,
              background: downloading ? "var(--bg-secondary)" : "rgba(168,85,247,0.15)",
              color: downloading ? "var(--text-dim)" : "var(--accent)",
              border: "1px solid var(--accent-border)",
              borderRadius: 6, padding: "7px 14px",
              fontSize: 9, fontWeight: 800, cursor: downloading ? "not-allowed" : "pointer",
              fontFamily: "var(--font-display)", letterSpacing: 2,
              transition: "all 0.2s",
              boxShadow: downloading ? "none" : "0 0 10px var(--accent-dim)",
            }}
            onMouseEnter={e => { if (!downloading) e.currentTarget.style.background = "var(--accent-dim)"; }}
            onMouseLeave={e => { if (!downloading) e.currentTarget.style.background = "rgba(168,85,247,0.15)"; }}
          >
            <span style={{ fontSize: 12 }}>{downloading ? "⏳" : "⬇"}</span>
            {downloading ? "GENERATING..." : "REPORT"}
          </button>
        </div>

        {/* Score ticker */}
        <div style={{ display: "flex", alignItems: "center", gap: 12, background: "var(--bg-secondary)", border: "1px solid var(--accent-border)", borderRadius: 8, padding: "6px 16px" }}>
          <ScoreBadge label="RED" score={scores.red_score} color="var(--red)" glow="var(--red-glow)" />
          <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 2 }}>
            <span style={{ color: "var(--accent)", fontFamily: "var(--font-display)", fontSize: 10, fontWeight: 900, letterSpacing: 2 }}>VS</span>
            <div style={{ width: 1, height: 20, background: "var(--accent-border)" }} />
          </div>
          <ScoreBadge label="BLUE" score={scores.blue_score} color="var(--cyan)" glow="var(--cyan-glow)" />
        </div>

        {/* Status + user */}
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <StatusPill on={red.connected} label="RED" color="var(--red)" />
          <StatusPill on={blue.connected} label="BLUE" color="var(--cyan)" />
          <div style={{ width: 1, height: 20, background: "var(--accent-border)" }} />
          <span style={{ color: "var(--text-primary)", fontSize: 12, fontFamily: "var(--font-ui)", letterSpacing: 1, fontWeight: 600 }}>
            &#9632; {username}
          </span>
          <button onClick={() => { logout(); nav("/login"); }} style={logoutBtn}>LOGOUT</button>
        </div>
      </header>

      {/* ═══ MAIN CONTENT ═══ */}
      {tab === "battle" ? (
        <div ref={containerRef} style={{ flex: 1, display: "grid", gridTemplateColumns: `${splitPct}% 8px ${100 - splitPct}%`, overflow: "hidden" }}>

          {/* ── RED HALF ── */}
          <div style={{ display: "flex", flexDirection: "column", overflow: "hidden", borderRight: "none" }}>
            {/* Red team header */}
            <div style={{ ...teamHeader, borderLeft: "3px solid var(--red)", background: "linear-gradient(90deg, rgba(244,63,94,0.08) 0%, var(--bg-secondary) 60%)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                <span style={{ fontSize: 16 }}>&#9760;</span>
                <span style={{ color: "var(--red)", fontFamily: "var(--font-display)", fontSize: 15, fontWeight: 900, letterSpacing: 4, textShadow: "0 0 12px var(--red-glow)" }}>RED ARSENAL</span>
              </div>
              <div style={{ display: "flex", gap: 6 }}>
                {redRunning > 0 && <Pill label={`${redRunning} ACTIVE`} color="var(--orange)" bg="rgba(251,146,60,0.12)" />}
                {redDone > 0 && <Pill label={`${redDone} DONE`} color="var(--text-dim)" bg="var(--bg-hover)" />}
              </div>
            </div>

            <div style={{ flex: 1, display: "grid", gridTemplateColumns: "1fr 1fr", overflow: "hidden", gap: 1, background: "var(--accent-border)" }}>
              {/* Red Terminal */}
              <div style={panel}>
                <div style={{ ...panelHeader, borderLeft: "2px solid var(--red)" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <span style={{ color: "var(--red)", fontSize: 8 }}>●</span>
                    <span style={{ color: "var(--orange)", fontSize: 8 }}>●</span>
                    <span style={{ color: "var(--green)", fontSize: 8 }}>●</span>
                    <span style={{ marginLeft: 4, color: "var(--text-primary)", fontWeight: 800, letterSpacing: 2, fontSize: 12 }}>ATTACK TERMINAL</span>
                  </div>
                  <span style={{ fontSize: 10, color: "var(--text-secondary)", fontFamily: "var(--font-ui)" }}>zsh</span>
                </div>
                <div ref={redTermRef} style={termBody}>
                  {redMessages.length === 0 && (
                    <div style={emptyState}>
                      <div style={{ fontSize: 28, marginBottom: 10, opacity: 0.3 }}>&#9760;</div>
                      <div style={{ color: "var(--text-secondary)", fontSize: 13, letterSpacing: 2 }}>AWAITING COMMANDS</div>
                    </div>
                  )}
                  {redMessages.map((m, i) => (
                    <div key={i} style={{ marginBottom: 10, animation: "slide-up 0.2s ease" }}>
                      <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 4 }}>
                        <span style={{ color: m.role === "operator" ? "var(--orange)" : "var(--red)", fontSize: 11, fontWeight: 800, fontFamily: "var(--font-ui)", letterSpacing: 1 }}>
                          {m.role === "operator" ? "▶ YOU" : "◈ RED AGENT"}
                        </span>
                      </div>
                      <div style={{
                        ...msgBubble,
                        background: m.role === "operator" ? "rgba(251,146,60,0.08)" : "var(--bg-secondary)",
                        borderLeft: `2px solid ${m.role === "operator" ? "var(--orange)" : "var(--red)"}`,
                        borderRadius: "0 8px 8px 0",
                      }}>{m.text}</div>
                    </div>
                  ))}
                  {redLoading && (
                    <div style={{ display: "flex", alignItems: "center", gap: 6, color: "var(--text-dim)", fontSize: 11 }}>
                      <span className="anim-pulse">●</span>
                      <span className="anim-pulse" style={{ animationDelay: "0.2s" }}>●</span>
                      <span className="anim-pulse" style={{ animationDelay: "0.4s" }}>●</span>
                      <span style={{ marginLeft: 4, fontFamily: "var(--font-ui)", letterSpacing: 1, fontSize: 13 }}>processing...</span>
                    </div>
                  )}
                </div>
                <div style={inputBar}>
                  <span style={{ color: "var(--red)", fontSize: 14, fontWeight: 900 }}>&#10095;</span>
                  <input
                    value={redInput}
                    onChange={e => setRedInput(e.target.value)}
                    onKeyDown={e => e.key === "Enter" && sendRed()}
                    placeholder="enter attack command..."
                    style={{ ...chatInput, borderColor: redInput ? "var(--red)" : "var(--accent-border)" }}
                  />
                  <button onClick={sendRed} disabled={redLoading} style={{ ...sendBtn, background: "var(--red)", opacity: redLoading ? 0.5 : 1 }}>&#10148;</button>
                </div>
              </div>

              {/* Red Logs */}
              <div style={panel}>
                <div style={{ ...panelHeader, borderLeft: "2px solid var(--red)" }}>
                  <span style={{ letterSpacing: 2, fontWeight: 800 }}>RED LOG</span>
                  <span style={{ background: "var(--red-dim)", color: "var(--red)", borderRadius: 10, padding: "2px 10px", fontSize: 11, fontWeight: 800 }}>{red.logs.length}</span>
                </div>
                <div style={logBody}>
                  {red.logs.length === 0 && <div style={emptyState}><span style={{ color: "var(--text-secondary)", fontSize: 13, letterSpacing: 2 }}>NO LOGS YET</span></div>}
                  {red.logs.map((l, i) => (
                    <LogRow key={i} log={l} fmtTime={fmtTime} />
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* ── Draggable Divider ── */}
          <div
            onMouseDown={onDividerMouseDown}
            style={{
              background: "var(--accent-border)",
              boxShadow: "0 0 16px var(--accent-glow)",
              cursor: "col-resize",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              zIndex: 10,
              transition: "background 0.15s, box-shadow 0.15s",
              position: "relative",
            }}
            onMouseEnter={e => { e.currentTarget.style.background = "var(--accent)"; e.currentTarget.style.boxShadow = "0 0 24px var(--accent-glow)"; }}
            onMouseLeave={e => { e.currentTarget.style.background = "var(--accent-border)"; e.currentTarget.style.boxShadow = "0 0 16px var(--accent-glow)"; }}
          >
            <div style={{ display: "flex", flexDirection: "column", gap: 3, alignItems: "center" }}>
              {[0,1,2,3,4].map(i => <div key={i} style={{ width: 2, height: 4, borderRadius: 1, background: "var(--accent)", opacity: 0.6 }} />)}
            </div>
          </div>

          {/* ── BLUE HALF ── */}
          <div style={{ display: "flex", flexDirection: "column", overflow: "hidden" }}>
            {/* Blue team header */}
            <div style={{ ...teamHeader, borderLeft: "3px solid var(--cyan)", background: "linear-gradient(90deg, rgba(34,211,238,0.08) 0%, var(--bg-secondary) 60%)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                <span style={{ fontSize: 16 }}>&#9681;</span>
                <span style={{ color: "var(--cyan)", fontFamily: "var(--font-display)", fontSize: 15, fontWeight: 900, letterSpacing: 4, textShadow: "0 0 12px var(--cyan-glow)" }}>BLUE SHIELD</span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                {blueRunning > 0 && <Pill label={`${blueRunning} ACTIVE`} color="var(--cyan)" bg="var(--cyan-dim)" />}
                {blueDone > 0 && <Pill label={`${blueDone} DONE`} color="var(--text-dim)" bg="var(--bg-hover)" />}
                {pendingFixes.length > 0 && (
                  <button onClick={approveAll} style={{ ...actionBtn, background: "rgba(52,211,153,0.15)", color: "var(--green)", border: "1px solid var(--green)" }}>
                    ✓ APPROVE ALL ({pendingFixes.length})
                  </button>
                )}
                <button onClick={sendReportToBlue} style={{ ...actionBtn, background: "var(--accent-dim)", color: "var(--accent)", border: "1px solid var(--accent-border)" }}>
                  ⟳ SEND REPORT
                </button>
              </div>
            </div>

            <div style={{ flex: 1, display: "grid", gridTemplateColumns: "1fr 1fr", overflow: "hidden", gap: 1, background: "var(--accent-border)" }}>
              {/* Blue Defense Terminal */}
              <div style={panel}>
                <div style={{ ...panelHeader, borderLeft: "2px solid var(--cyan)" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <span style={{ color: "var(--red)", fontSize: 8 }}>●</span>
                    <span style={{ color: "var(--orange)", fontSize: 8 }}>●</span>
                    <span style={{ color: "var(--green)", fontSize: 8 }}>●</span>
                    <span style={{ marginLeft: 4, color: "var(--text-primary)", fontWeight: 800, letterSpacing: 2, fontSize: 12 }}>DEFENSE TERMINAL</span>
                  </div>
                  <span style={{ fontSize: 10, color: "var(--text-secondary)", fontFamily: "var(--font-ui)" }}>shield</span>
                </div>
                <div ref={blueTermRef} style={termBody}>
                  {!blueStarted && (
                    <div style={emptyState}>
                      <div style={{ fontSize: 28, marginBottom: 10, opacity: 0.3 }}>&#9681;</div>
                      <div style={{ color: "var(--text-secondary)", fontSize: 13, letterSpacing: 2 }}>CLICK SEND REPORT</div>
                      <div style={{ color: "var(--text-secondary)", fontSize: 11, letterSpacing: 1, marginTop: 6 }}>to start defense analysis</div>
                    </div>
                  )}
                  {blueStarted && pendingFixes.length === 0 && blueMessages.length === 0 && (
                    <div style={emptyState}>
                      <div style={{ fontSize: 28, marginBottom: 10, opacity: 0.3 }}>&#9681;</div>
                      <div style={{ color: "var(--text-secondary)", fontSize: 13, letterSpacing: 2 }}>PROCESSING...</div>
                    </div>
                  )}

                  {/* Blue messages first — stay at top */}
                  {blueStarted && blueMessages.map((m, i) => (
                    <div key={i} style={{ marginBottom: 10, animation: "slide-up 0.2s ease" }}>
                      <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 4 }}>
                        <span style={{ color: m.role === "system" ? "var(--yellow)" : "var(--cyan)", fontSize: 11, fontWeight: 800, fontFamily: "var(--font-ui)", letterSpacing: 1 }}>
                          {m.role === "system" ? "⚡ SYSTEM" : "◈ BLUE AGENT"}
                        </span>
                      </div>
                      <div style={{
                        ...msgBubble,
                        background: m.role === "system" ? "rgba(251,191,36,0.06)" : "var(--cyan-dim)",
                        borderLeft: `2px solid ${m.role === "system" ? "var(--yellow)" : "var(--cyan)"}`,
                        borderRadius: "0 8px 8px 0",
                      }}>{m.text}</div>
                    </div>
                  ))}

                  {/* Pending fix cards at the bottom — visible after auto-scroll */}
                  {blueStarted && pendingFixes.length > 0 && (
                    <div style={{ borderTop: "1px solid var(--accent-border)", marginTop: 8, paddingTop: 10 }}>
                      <div style={{ fontSize: 10, color: "var(--accent)", letterSpacing: 2, fontWeight: 800, marginBottom: 8, fontFamily: "var(--font-ui)" }}>
                        ⚠ {pendingFixes.length} FIXES PENDING APPROVAL
                      </div>
                      {pendingFixes.map(f => (
                        <div key={f.fix_id} style={{
                          marginBottom: 8,
                          padding: "10px 12px",
                          background: "var(--bg-secondary)",
                          borderRadius: "0 8px 8px 0",
                          borderLeft: `3px solid ${sevColor[f.severity] || "var(--yellow)"}`,
                          animation: "slide-up 0.2s ease",
                        }}>
                          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 5 }}>
                            <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                              <span style={{ fontSize: 11, fontWeight: 900, color: sevColor[f.severity] || "var(--yellow)", background: `${sevColor[f.severity] || "var(--yellow)"}20`, padding: "2px 8px", borderRadius: 4, letterSpacing: 1 }}>
                                {f.severity.toUpperCase()}
                              </span>
                              <span style={{ fontSize: 13, fontWeight: 700, color: "var(--text-primary)" }}>{f.category.replace(/_/g, " ")}</span>
                            </div>
                            <div style={{ display: "flex", gap: 4 }}>
                              <button onClick={() => approveFix(f.fix_id)} style={applyBtn}>✓ APPLY</button>
                              <button onClick={() => blueApi.rejectFix(f.fix_id).then(() => setPendingFixes(p => p.filter(x => x.fix_id !== f.fix_id)))} style={skipBtn}>✕ SKIP</button>
                            </div>
                          </div>
                          <div style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.6 }}>{f.description}</div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              {/* Blue Logs */}
              <div style={panel}>
                <div style={{ ...panelHeader, borderLeft: "2px solid var(--cyan)" }}>
                  <span style={{ letterSpacing: 2, fontWeight: 800 }}>BLUE LOG</span>
                  <span style={{ background: "var(--cyan-dim)", color: "var(--cyan)", borderRadius: 10, padding: "2px 10px", fontSize: 11, fontWeight: 800 }}>{blue.logs.length}</span>
                </div>
                <div style={logBody}>
                  {!blueStarted && (
                    <div style={emptyState}>
                      <span style={{ color: "var(--text-secondary)", fontSize: 13, letterSpacing: 2 }}>STANDBY</span>
                      <span style={{ color: "var(--text-dim)", fontSize: 11, marginTop: 6, letterSpacing: 1 }}>waiting for command</span>
                    </div>
                  )}
                  {blueStarted && blue.logs.length === 0 && <div style={emptyState}><span style={{ color: "var(--text-secondary)", fontSize: 13, letterSpacing: 2 }}>NO LOGS YET</span></div>}
                  {blueStarted && blue.logs.map((l, i) => (
                    <LogRow key={i} log={l} fmtTime={fmtTime} />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>

      ) : (
        /* ═══ SCOREBOARD ═══ */
        <div style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", padding: "40px 20px", overflow: "auto" }}>
          <div style={{ fontFamily: "var(--font-display)", fontSize: 32, fontWeight: 900, color: "var(--accent)", letterSpacing: 8, marginBottom: 8, textShadow: "0 0 30px var(--accent-glow)" }}>LEADERBOARD</div>
          <div style={{ color: "var(--text-secondary)", fontSize: 12, letterSpacing: 4, marginBottom: 40, fontFamily: "var(--font-ui)" }}>LIVE SCORE TRACKING</div>

          <div style={{ display: "grid", gridTemplateColumns: "1fr auto 1fr", gap: 24, width: "100%", maxWidth: 760, marginBottom: 48 }}>
            <div style={{ ...scoreCard, borderColor: "var(--red)", boxShadow: "0 0 40px rgba(244,63,94,0.15), inset 0 0 20px rgba(244,63,94,0.05)" }}>
              <div style={{ fontSize: 9, color: "var(--red)", letterSpacing: 4, fontFamily: "var(--font-ui)", marginBottom: 12, fontWeight: 700 }}>&#9760; RED TEAM</div>
              <div style={{ fontSize: 56, fontWeight: 900, color: "var(--red)", fontFamily: "var(--font-display)", textShadow: "0 0 30px var(--red-glow)", lineHeight: 1 }}>{scores.red_score}</div>
              <div style={{ fontSize: 9, color: "var(--text-dim)", marginTop: 8, letterSpacing: 2 }}>ATTACK POINTS</div>
            </div>

            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 8 }}>
              <div style={{ width: 1, flex: 1, background: "linear-gradient(to bottom, transparent, var(--accent-border))" }} />
              <span style={{ fontSize: 18, fontFamily: "var(--font-display)", color: "var(--accent)", fontWeight: 900, textShadow: "0 0 20px var(--accent-glow)" }}>VS</span>
              <div style={{ width: 1, flex: 1, background: "linear-gradient(to top, transparent, var(--accent-border))" }} />
            </div>

            <div style={{ ...scoreCard, borderColor: "var(--cyan)", boxShadow: "0 0 40px rgba(34,211,238,0.15), inset 0 0 20px rgba(34,211,238,0.05)" }}>
              <div style={{ fontSize: 9, color: "var(--cyan)", letterSpacing: 4, fontFamily: "var(--font-ui)", marginBottom: 12, fontWeight: 700 }}>&#9681; BLUE TEAM</div>
              <div style={{ fontSize: 56, fontWeight: 900, color: "var(--cyan)", fontFamily: "var(--font-display)", textShadow: "0 0 30px var(--cyan-glow)", lineHeight: 1 }}>{scores.blue_score}</div>
              <div style={{ fontSize: 9, color: "var(--text-dim)", marginTop: 8, letterSpacing: 2 }}>DEFENSE POINTS</div>
            </div>
          </div>

          {/* Score history */}
          <div style={{ width: "100%", maxWidth: 760, background: "var(--bg-secondary)", border: "1px solid var(--accent-border)", borderRadius: 12, overflow: "hidden" }}>
            <div style={{ padding: "12px 20px", borderBottom: "1px solid var(--accent-border)", display: "flex", alignItems: "center", gap: 8 }}>
              <span style={{ fontSize: 11, color: "var(--accent)", letterSpacing: 3, fontFamily: "var(--font-display)", fontWeight: 800 }}>SCORE HISTORY</span>
              <span style={{ fontSize: 9, color: "var(--text-dim)", background: "var(--accent-dim)", padding: "1px 8px", borderRadius: 8 }}>{scores.history.length}</span>
            </div>
            {scores.history.length === 0 ? (
              <div style={{ padding: "32px", textAlign: "center", color: "var(--text-dim)", fontSize: 11, letterSpacing: 2 }}>NO POINTS AWARDED YET</div>
            ) : (
              <div style={{ overflowY: "auto", maxHeight: 300 }}>
                {[...scores.history].reverse().slice(0, 20).map((h, i) => (
                  <div key={i} style={{ display: "flex", alignItems: "center", gap: 16, padding: "8px 20px", borderBottom: "1px solid rgba(168,85,247,0.08)", background: i % 2 === 0 ? "transparent" : "rgba(168,85,247,0.02)" }}>
                    <span style={{ color: h.team === "red" ? "var(--red)" : "var(--cyan)", fontWeight: 900, width: 52, fontFamily: "var(--font-display)", fontSize: 9, letterSpacing: 1 }}>{h.team.toUpperCase()}</span>
                    <span style={{ color: "var(--green)", fontWeight: 800, width: 48, fontSize: 13, fontFamily: "var(--font-display)" }}>+{h.points}</span>
                    <span style={{ color: "var(--text-secondary)", fontSize: 11, flex: 1 }}>{h.reason}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

// ── Sub-components ────────────────────────────────────────────────────────────

function LogRow({ log, fmtTime }: { log: LogEntry; fmtTime: (ts: string) => string }) {
  const levStyle: Record<string, { color: string; bg: string }> = {
    INFO: { color: "var(--green)", bg: "rgba(52,211,153,0.15)" },
    WARN: { color: "var(--yellow)", bg: "rgba(251,191,36,0.15)" },
    ERROR: { color: "var(--red)", bg: "rgba(244,63,94,0.15)" },
  };
  const s = levStyle[log.level] || { color: "var(--text-primary)", bg: "transparent" };
  return (
    <div style={{ display: "flex", gap: 8, fontSize: 12, padding: "4px 6px", borderRadius: 4, marginBottom: 3, alignItems: "flex-start" }}>
      <span style={{ color: "var(--text-secondary)", flexShrink: 0, fontFamily: "var(--font-mono)", minWidth: 58, fontSize: 11 }}>{fmtTime(log.timestamp)}</span>
      <span style={{ color: s.color, background: s.bg, flexShrink: 0, padding: "1px 7px", borderRadius: 4, fontWeight: 800, fontSize: 10, lineHeight: "18px", letterSpacing: 0.5, minWidth: 40, textAlign: "center" }}>{log.level}</span>
      <span style={{ color: "var(--text-primary)", lineHeight: 1.7, wordBreak: "break-word", fontSize: 12 }}>{log.message}</span>
    </div>
  );
}

function TabBtn({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) {
  return (
    <button onClick={onClick} style={{
      background: active ? "var(--accent-dim)" : "transparent",
      color: active ? "var(--accent)" : "var(--text-secondary)",
      border: "none",
      padding: "8px 20px",
      fontSize: 11,
      fontWeight: 800,
      cursor: "pointer",
      fontFamily: "var(--font-display)",
      letterSpacing: 2,
      transition: "all 0.15s",
      borderBottom: active ? "2px solid var(--accent)" : "2px solid transparent",
    }}>{label}</button>
  );
}

function ScoreBadge({ label, score, color, glow }: { label: string; score: number; color: string; glow: string }) {
  return (
    <div style={{ textAlign: "center" }}>
      <div style={{ fontSize: 26, fontWeight: 900, color, fontFamily: "var(--font-display)", textShadow: `0 0 16px ${glow}`, lineHeight: 1 }}>{score}</div>
      <div style={{ fontSize: 9, color: "var(--text-secondary)", letterSpacing: 3, fontFamily: "var(--font-ui)", marginTop: 3 }}>{label}</div>
    </div>
  );
}

function StatusPill({ on, label, color }: { on: boolean; label: string; color: string }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 6, background: on ? `${color}18` : "transparent", border: `1px solid ${on ? color : "var(--text-dim)"}`, borderRadius: 12, padding: "4px 10px", transition: "all 0.3s" }}>
      <span className={on ? "anim-pulse" : ""} style={{ width: 7, height: 7, borderRadius: "50%", background: on ? color : "var(--text-dim)", display: "block" }} />
      <span style={{ fontSize: 10, color: on ? color : "var(--text-secondary)", fontFamily: "var(--font-ui)", letterSpacing: 1, fontWeight: 800 }}>{label}</span>
    </div>
  );
}

function Pill({ label, color, bg }: { label: string; color: string; bg: string }) {
  return (
    <span style={{ color, background: bg, borderRadius: 10, padding: "3px 10px", fontSize: 10, fontWeight: 800, letterSpacing: 1, fontFamily: "var(--font-ui)" }}>{label}</span>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────

const topBar: CSSProperties = {
  display: "flex", justifyContent: "space-between", alignItems: "center",
  padding: "8px 20px", background: "var(--bg-primary)",
  borderBottom: "1px solid var(--accent-border)",
  boxShadow: "0 2px 20px rgba(0,0,0,0.4)",
  flexShrink: 0, zIndex: 20,
};
const logoBadge: CSSProperties = {
  width: 38, height: 38, borderRadius: 10,
  background: "var(--accent-dim)", border: "1px solid var(--accent-border)",
  display: "flex", alignItems: "center", justifyContent: "center", color: "var(--accent)",
};
const teamHeader: CSSProperties = {
  display: "flex", justifyContent: "space-between", alignItems: "center",
  padding: "10px 16px", borderBottom: "1px solid var(--accent-border)", flexShrink: 0,
};
const panel: CSSProperties = {
  display: "flex", flexDirection: "column", overflow: "hidden",
  background: "var(--bg-primary)",
};
const panelHeader: CSSProperties = {
  padding: "10px 14px", fontSize: 12, fontWeight: 800, letterSpacing: 2,
  color: "var(--text-primary)", borderBottom: "1px solid var(--accent-border)",
  flexShrink: 0, display: "flex", justifyContent: "space-between", alignItems: "center",
  background: "var(--bg-secondary)",
};
const termBody: CSSProperties = { flex: 1, minHeight: 0, overflowY: "auto", padding: "14px" };
const logBody: CSSProperties = { flex: 1, minHeight: 0, overflowY: "auto", padding: "10px 12px" };
const msgBubble: CSSProperties = { padding: "10px 14px", fontSize: 13, marginTop: 3, lineHeight: 1.7 };
const inputBar: CSSProperties = {
  display: "flex", alignItems: "center", gap: 8, padding: "10px 14px",
  borderTop: "1px solid var(--accent-border)", flexShrink: 0,
  background: "var(--bg-secondary)",
};
const chatInput: CSSProperties = {
  flex: 1, background: "var(--bg-input)", border: "1px solid var(--accent-border)",
  borderRadius: 6, padding: "9px 14px", color: "var(--text-primary)",
  fontFamily: "var(--font-mono)", fontSize: 13, outline: "none", transition: "border-color 0.2s",
};
const sendBtn: CSSProperties = {
  background: "var(--accent)", color: "var(--bg-void)", border: "none",
  borderRadius: 6, padding: "9px 16px", fontWeight: 800, cursor: "pointer",
  fontFamily: "var(--font-mono)", fontSize: 14, transition: "opacity 0.2s",
};
const actionBtn: CSSProperties = {
  border: "none", borderRadius: 6, padding: "5px 12px", fontSize: 11,
  fontWeight: 800, cursor: "pointer", fontFamily: "var(--font-mono)", letterSpacing: 1,
};
const applyBtn: CSSProperties = {
  background: "rgba(52,211,153,0.15)", color: "var(--green)", border: "1px solid var(--green)",
  borderRadius: 4, padding: "3px 10px", fontSize: 10, fontWeight: 800, cursor: "pointer",
  fontFamily: "var(--font-mono)", letterSpacing: 0.5,
};
const skipBtn: CSSProperties = {
  background: "var(--red-dim)", color: "var(--red)", border: "1px solid rgba(244,63,94,0.3)",
  borderRadius: 4, padding: "3px 10px", fontSize: 10, fontWeight: 800, cursor: "pointer",
  fontFamily: "var(--font-mono)", letterSpacing: 0.5,
};
const logoutBtn: CSSProperties = {
  background: "var(--red-dim)", color: "var(--red)", border: "1px solid rgba(244,63,94,0.3)",
  borderRadius: 6, padding: "6px 14px", fontSize: 10, fontWeight: 700, cursor: "pointer",
  fontFamily: "var(--font-ui)", letterSpacing: 1, transition: "all 0.2s",
};
const scoreCard: CSSProperties = {
  background: "var(--bg-card)", border: "1px solid", borderRadius: 16,
  padding: "28px 24px", textAlign: "center",
};
const emptyState: CSSProperties = {
  display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
  height: "100%", minHeight: 120, opacity: 0.6,
};
